from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext

import numpy

setup(
    cmdclass = {'build_ext': build_ext},
    ext_modules = [Extension("DRRGenerate",
                             sources=["DRRGenerate.pyx"],
                             include_dirs=[numpy.get_include(), 
                                           "F:\\ITK\\release\\include\\ITK-5.3",
                                           "F:\\code\\python\\iMIA\\MyDRR\\DigitallyReconstructedRadiographs\\DRRModule\\include"
                                           ],
                             library_dirs = ["F:\\code\\python\\iMIA\\MyDRR\\DigitallyReconstructedRadiographs\\DRRModule\\lib",
                                            "F:\\ITK\\release\\lib",
                                            "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.19041.0\\um\\x64"
                                            ],
                             libraries = ["DRRGenerate", 
                                          "Advapi32",
                                          "shell32",
                                          "WS2_32",
                                          "rpcrt4",
                                          'hdf5_hl_cpp-static',
                                          'ITKBiasCorrection-5.3',
                                          'ITKColormap-5.3',
                                          'ITKCommon-5.3',
                                          'ITKConvolution-5.3',
                                          'ITKDeformableMesh-5.3',
                                          'ITKDenoising-5.3',
                                          'ITKDICOMParser-5.3',
                                          'ITKDiffusionTensorImage-5.3',
                                          'itkdouble-conversion-5.3',
                                          'ITKEXPAT-5.3',
                                          'ITKFastMarching-5.3',
                                          'ITKFFT-5.3',
                                          'itkgdcmcharls-5.3',
                                          'itkgdcmCommon-5.3',
                                          'itkgdcmDICT-5.3',
                                          'itkgdcmDSED-5.3',
                                          'itkgdcmIOD-5.3',
                                          'itkgdcmjpeg12-5.3',
                                          'itkgdcmjpeg16-5.3',
                                          'itkgdcmjpeg8-5.3',
                                          'itkgdcmMEXD-5.3',
                                          'itkgdcmMSFF-5.3',
                                          'itkgdcmopenjp2-5.3',
                                          'itkgdcmsocketxx-5.3',
                                          'ITKgiftiio-5.3',
                                          'itkhdf5-static-5.3',
                                          'itkhdf5_cpp-static-5.3',
                                          'itkhdf5_hl-static-5.3',
                                          'ITKImageFeature-5.3',
                                          'ITKImageIntensity-5.3',
                                          'ITKIOBioRad-5.3',
                                          'ITKIOBMP-5.3',
                                          'ITKIOBruker-5.3',
                                          'ITKIOCSV-5.3',
                                          'ITKIOGDCM-5.3',
                                          'ITKIOGE-5.3',
                                          'ITKIOGIPL-5.3',
                                          'ITKIOHDF5-5.3',
                                          'ITKIOImageBase-5.3',
                                          'ITKIOIPL-5.3',
                                          'ITKIOJPEG-5.3',
                                          'ITKIOJPEG2000-5.3',
                                          'ITKIOLSM-5.3',
                                          'ITKIOMeshBase-5.3',
                                          'ITKIOMeshBYU-5.3',
                                          'ITKIOMeshFreeSurfer-5.3',
                                          'ITKIOMeshGifti-5.3',
                                          'ITKIOMeshOBJ-5.3',
                                          'ITKIOMeshOFF-5.3',
                                          'ITKIOMeshVTK-5.3',
                                          'ITKIOMeta-5.3',
                                          'ITKIOMINC-5.3',
                                          'ITKIOMRC-5.3',
                                          'ITKIONIFTI-5.3',
                                          'ITKIONRRD-5.3',
                                          'ITKIOPNG-5.3',
                                          'ITKIOSiemens-5.3',
                                          'ITKIOSpatialObjects-5.3',
                                          'ITKIOStimulate-5.3',
                                          'ITKIOTIFF-5.3',
                                          'ITKIOTransformBase-5.3',
                                          'ITKIOTransformHDF5-5.3',
                                          'ITKIOTransformInsightLegacy-5.3',
                                          'ITKIOTransformMatlab-5.3',
                                          'ITKIOVTK-5.3',
                                          'ITKIOXML-5.3',
                                          'itkjpeg-5.3',
                                          'ITKKLMRegionGrowing-5.3',
                                          'ITKLabelMap-5.3',
                                          'itklbfgs-5.3',
                                          'ITKMarkovRandomFieldsClassifiers-5.3',
                                          'ITKMathematicalMorphology-5.3',
                                          'ITKMesh-5.3',
                                          'ITKMetaIO-5.3',
                                          'itkminc2-5.3',
                                          'itkNetlibSlatec-5.3',
                                          'ITKniftiio-5.3',
                                          'ITKNrrdIO-5.3',
                                          'itkopenjpeg-5.3',
                                          'ITKOptimizers-5.3',
                                          'ITKOptimizersv4-5.3',
                                          'ITKPath-5.3',
                                          'ITKPDEDeformableRegistration-5.3',
                                          'itkpng-5.3',
                                          'ITKPolynomials-5.3',
                                          'ITKQuadEdgeMesh-5.3',
                                          'ITKQuadEdgeMeshFiltering-5.3',
                                          'ITKRegionGrowing-5.3',
                                          'ITKRegistrationMethodsv4-5.3',
                                          'ITKSmoothing-5.3',
                                          'ITKSpatialObjects-5.3',
                                          'ITKStatistics-5.3',
                                          'itksys-5.3',

                                          'itktestlib-5.3',
                                          'itktiff-5.3',
                                          'ITKTransform-5.3',
                                          'ITKTransformFactory-5.3',
                                          'itkv3p_netlib-5.3',
                                          'itkvcl-5.3',
                                          'ITKVideoCore-5.3',
                                          'ITKVideoIO-5.3',
                                          'itkvnl-5.3',
                                          'ITKVNLInstantiation-5.3',
                                          'itkvnl_algo-5.3',
                                          'ITKVTK-5.3',
                                          'ITKWatersheds-5.3',
                                          'itkzlib-5.3',
                                          'ITKznz-5.3'],
                             language = "c++")]
)